config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  delete 'subscriptions/:id', to: 'subscriptions#cancel', as: 'cancel_subscription'
  delete 'ported_subscriptions/:id', to: 'subscriptions#specialist_cancel', as: 'specialist_cancel_subscription'
  put 'subscriptions/:id', to: 'subscriptions#update', as: 'update_subscription'

  if Rails.env.production? || Rails.env.staging?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username == ENV.fetch('SIDEKIQ_USERNAME') && password == ENV.fetch('SIDEKIQ_PASSWORD')
    end
  end
  mount Sidekiq::Web => '/sidekiq'

  devise_for :admin_users, ActiveAdmin::Devise.config
  begin
    ActiveAdmin.routes(self)
  rescue ActiveRecord::StatementInvalid, PG::UndefinedTable => e
    Rails.logger.info "ActiveAdmin could not load: #{e.message}"
  end
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  } do
  end

  devise_scope :user do
    get '/squarespace' => 'users/sessions#squarespace'
    get '/squarespace_destroy' => 'users/sessions#squarespace_destroy'
  end

  root to: 'landing_page#show'
  get 'app_config' => 'home#app_config', format: 'js'
  get 'marketplace' => 'home#marketplace'
  get 'r/:token' => 'referrals#show', as: :referrals
  get 'q-and-a-forum' => 'home#q_and_a_forum', as: :q_and_a_forum

  get '/ask-a-specialist/search' => 'forum_questions#search', as: :forum_search
  resources :forum_questions, path: 'ask-a-specialist', param: :url
  resources :forum_answers, only: :create
  get '/ask-a-specialist/upvote/:id' => 'forum_votes#upvote'
  get '/ask-a-specialist/downvote/:id' => 'forum_votes#downvote'
  get '/forum_subscriptions/create' => 'forum_subscriptions#create'
  get '/forum_subscriptions/upgrade' => 'forum_subscriptions#upgrade'
  get '/forum_subscriptions/cancel' => 'forum_subscriptions#cancel'

  get '/notifications_settings' => 'notifications#route'

  get '/exams/:uuid' => 'exams#show'

  resources :turnkey_pages, only: %i[index show create new], path: 'turnkey'
  #  resources :turnkey_solutions # , only: :create
  post '/turnkey/:id' => 'turnkey_pages#create'
  patch '/turnkey/:id' => 'turnkey_pages#update'
  get '/mute_project/:id' => 'project_mutes#toggle'

  resources :feedback_requests, only: %i[create new]
  resources :businesses, only: %i[new create show]
  resource :business, only: %i[edit] do
    patch '/' => 'businesses#update', as: :update
  end
  get '/business' => 'business_dashboard#show', as: :business_dashboard

  concern :favoriteable do
    resources :favorites, only: [] do
      post :toggle, on: :collection
    end
  end
  resources :flags, only: %i[new create]

  namespace :business do
    get '/personalize' => 'personalize#quiz'
    post '/personalize' => 'personalize#quiz'
    get '/personalize_book' => 'personalize#book'
    get '/onboarding' => 'onboarding#index'
    post '/onboarding' => 'onboarding#subscribe'
    get '/upgrade' => 'upgrade#index'
    get '/upgrade/buy' => 'upgrade#buy'
    post '/upgrade/buy' => 'upgrade#subscribe'
    resources :risks, only: %i[index show]
    get '/reports/risks' => 'reports#risks'
    get '/reports/organizations' => 'reports#organizations'
    get '/reports/financials' => 'reports#financials'
    resources :file_folders, only: %i[index show]
    resources :exam_management, only: %i[index show] do
      get :portal, on: :member
    end
    resources :file_docs
    resources :upgrade
    resources :addons, only: %i[index]
    resources :seats, only: %i[index new] do
      delete :unassign
      post :assign
    end
    post '/seats/buy' => 'seats#buy'
    resources :compliance_policies, only: %i[show index] do
      get :entire, on: :collection
    end
    get 'annual_reviews/:id/:revcat', to: 'annual_reviews#revcat'
    resources :annual_reviews, only: %i[new create show destroy index edit update]
    resources :annual_reports, only: %i[new create index update]
    resources :teams, only: %i[new create show edit index update destroy]
    resources :team_members, only: %i[new create edit update destroy]
    resources :tasks, only: %i[new update create destroy show edit index]
    resources :audit_requests, only: %i[index update create new edit show destroy]
    put '/audit_requests' => 'audit_requests#update'
    resource :help, only: :show do
      resource :questions
    end
    resource :projects, only: %i[index]

    get '/projects/new/:local_project_id' => 'projects#new'

    get 'settings' => 'settings#show'
    get 'settings/:id' => 'settings#show'

    get 'profile' => 'profile#show'

    resources :specialists, only: :index
    concerns :favoriteable
    resources :messages
    resources :financials do
      get :invoice, on: :member
    end

    get 'projects/:project_id/interview/:specialist_username' => 'project_dashboard#show', as: :project_dashboard_interview
    get 'projects/:project_id/dashboard' => 'project_dashboard#show', as: :project_dashboard

    scope 'projects/:project_id' do
      resources :project_messages, path: 'messages(/:specialist_username)'
      resources :project_ends, path: 'end'
      resources :project_extensions, path: 'extension'
      resource :project_rating, path: 'rating'
      resource :project_overview, path: 'overview(/:specialist_username)', only: :show
    end

    get 'project_posts/:id' => 'projects#show_post'
    get 'project_posts/:id/edit' => 'projects#update_post'

    resources :projects do
      post :post, on: :member
      get :copy, on: :member

      resources :job_applications, path: 'applications'
      resources :hires
      resources :documents, path: 'documents(/:specialist_username)'
      resources :answers, only: :create
      resources :flags, only: %i[new create]
      resources :timesheets
      resources :project_issues, path: 'issues'
    end

    resources :job_applications do
      post :shortlist
      post :hide
    end
  end

  resources :tos_agreement, only: %i[create]

  resources :employees, path: 'employee', only: %i[new create index]
  # get '/employees/mirror/:business_id', to: 'employees#mirror', as: 'mirror_business'
  # get '/employees/stop-mirror', to: 'employees#stop_mirror', as: 'stop_mirror_business'
  resources :reminders, only: ['index']
  namespace :specialists, path: 'specialist' do
    get '/onboarding' => 'onboarding#index'
    post '/onboarding' => 'onboarding#subscribe'
    get '/' => 'dashboard#show', as: :dashboard
    get '/locked' => 'dashboard#locked'
    resources :tasks, only: %i[new update create destroy edit show index]
    resources :addons, only: %i[index]
    resource :help, only: :show do
      resource :questions
    end
    get 'profile' => 'profile#show'
    get 'settings/:page', to: 'settings#show', page: /general|users|roles|security|subscriptions|billings|notifications/
    resource :settings, only: :show do
      resource :password
      resource :contact_information, only: %i[show update]
      # resource :referrals, only: :show
      resources :subscription_settings, as: :subscriptions, path: 'subscriptions', only: %i[index update]
      resource :delete_account
      resources :delete_managed_accounts, only: :destroy
      resource :payment_settings, as: :payment, path: 'payment' do
        get :new_card
        post :create_card
        post :create_bank
        delete 'delete_card/:id', to: 'payment_settings#delete_card', as: 'delete_card'
        patch 'make_primary/:id', to: 'payment_settings#make_primary', as: 'make_primary'
        patch '/specialist/settings/payment/:id/validate', to: 'payment_settings#validate', as: 'validate'
      end
      resource :team

      resources :bank_accounts do
        patch :make_primary
      end
      resources :notification_settings, as: :notifications, path: 'notifications', only: %i[index update]
    end

    resources :ported_businesses, only: %i[index new create]
    get '/ported_businesses/buy' => 'ported_businesses#buy'
    post '/ported_businesses/buy' => 'ported_businesses#subscribe'
    delete '/ported_businesses/:id', to: 'ported_businesses#delete', as: 'delete_ported_businesses'
    resources :invitations, only: %i[create destroy]
    resources :projects, path: 'my-projects'
    concerns :favoriteable
    resources :messages
    resources :financials do
      get :invoice, on: :member
    end
  end

  get '/specialistmarketplace' => 'specialists#index'
  resources :specialists, only: %i[index new create show]
  get '/profile/:id', to: 'specialists#edit', as: 'employee_profile'
  resource :specialist, only: %i[edit] do
    patch '/' => 'specialists#update', as: :update
  end

  resources :project_invites, path: 'invite'

  resources :projects, only: %i[index show] do
    scope module: 'projects' do
      resources :job_applications, path: 'applications'
      resource :dashboard, only: :show
      resources :messages
      resources :documents
      resources :questions, only: :create
      resources :flags, only: %i[new create]
      resources :timesheets
      resources :issues
      resources :shares
      resource :project_end, path: 'end', as: :end
      resource :project_extension, path: 'extension', as: :extension
      resource :rating
      resource :overview, only: :show
    end
  end

  resources :notifications
  resources :email_threads, path: 'email', only: :create

  namespace :stripe do
    resources :webhooks, only: :create
  end

  namespace :api do
    get 'static_collection' => 'static_collection#index'
    post 'exams/:uuid' => 'exams#email'
    patch 'exams/:uuid' => 'exams#show'

    resources :skills, only: :index
    resources :users, only: [] do
      collection do
        post :sign_in, to: 'authentication#create'
        delete :sign_out, to: 'authentication#destroy'
        post :password, to: 'passwords#create'
        put :password, to: 'passwords#update'
      end

app/controllers/specialist_dashboard_controller.rb
# frozen_string_literal: true
class SpecialistDashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :require_specialist!

  def show
    @specialist = Specialist.preload_associations.find(current_user.specialist.id)
  end
end

app/views/specialist_dashboard/show.html.slim
- header_class ''
- Specialist::Decorator.decorate(@specialist).tap do |specialist|
  #specialist-dashboard.pseudo-table.row
    .tr
      .td.col-xs-12.col-sm-4.col-md-3.va-top
        .panel.panel-default.profile-info
          .panel-heading
            h3 Profile
          .panel-body
            - if specialist.photo
              .logo= image_tag specialist.photo_url(:thumb), class: 'img-responsive'
            h3.text-center= specialist
            .text-center= specialist.render_stars

            br

            .icon-list
              .item
                i.icon.maxicons2-navigation.text-muted
                span= specialist.city_state_country
              .item
                i.icon.maxicons1-building.text-muted
                span= specialist.industries.map(&:name).join(', ')
              .item
                i.icon.maxicons1-earth.text-muted
                span= specialist.jurisdictions.map(&:name).join(', ')
              .item
                i.icon.maxicons1-bag.text-muted
                span= pluralize specialist.years_of_experience, 'Year Experience', 'Years Experience'
              - if specialist.former_regulator?
                .item
                  i.icon.maxicons2-place.text-muted
                  span Former Regulator

            = simple_form_for Specialist::Form.find(specialist.id), remote: true, url: update_specialist_path, html: { class: 'm-y-2' } do |f|
              = hidden_field_tag 'redirect_to', specialist_dashboard_path
              = f.input :public_profile, as: :radio_pills, collection: [['Public', true], ['Private', false]], btn_class: 'btn-default btn-sm', label: false, hint: false, input_html: { data: { autosubmit: 'true' } }

            .text-center.p-b-1= link_to 'Edit Profile', edit_specialist_path, class: 'link'

      .td.col-xs-12.col-sm-8.col-md-9.va-top
        .panel.panel-default
          .panel-heading
            h3 My Projects
            .dropdown.visible-sm.visible-xs
              button.btn.btn-default.dropdown-toggle type="button" data-toggle="dropdown"
                'Filter
                span.caret
              ul.dropdown-menu.dropdown-menu-right
                li.active= link_to '#projects-active', data: { toggle: 'tab', "remote-load" => true, url: specialist_projects_path(filter: 'active'), 'toggle-sync' => true } do
                  i.icon.maxicons2-clock
                  span Active
                li= link_to '#projects-pending', data: { toggle: 'tab', "remote-load" => true, url: specialist_projects_path(filter: 'pending'), 'toggle-sync' => true } do
                  i.icon.maxicons1-load-77
                  span Pending
                li= link_to '#projects-favorite', data: { toggle: 'tab', "remote-load" => true, url: specialist_projects_path(filter: 'favorite'), 'toggle-sync' => true } do
                  i.icon.maxicons2-editor
                  span Favorite
                li= link_to '#projects-complete', data: { toggle: 'tab', "remote-load" => true, url: specialist_projects_path(filter: 'complete'), 'toggle-sync' => true } do
                  i.icon.maxicons1-check
                  span Complete
            ul#js-project-filters.nav.nav-pills.visible-md.visible-lg
              li.active= link_to '#projects-active', data: { toggle: 'tab', "remote-load" => true, url: specialist_projects_path(filter: 'active'), 'toggle-sync' => true } do
                i.icon.maxicons2-clock
                span Active
              li= link_to '#projects-pending', data: { toggle: 'tab', "remote-load" => true, url: specialist_projects_path(filter: 'pending'), 'toggle-sync' => true } do
                i.icon.maxicons1-load-77
                span Pending
              li= link_to '#projects-favorite', data: { toggle: 'tab', "remote-load" => true, url: specialist_projects_path(filter: 'favorite'), 'toggle-sync' => true } do
                i.icon.maxicons2-editor
                span Drafts
              li= link_to '#projects-complete', data: { toggle: 'tab', "remote-load" => true, url: specialist_projects_path(filter: 'complete'), 'toggle-sync' => true } do
                i.icon.maxicons1-check
                span Complete
          .panel-body.p-b-0
            .tab-content
              #projects-active.tab-pane.active
              #projects-pending.tab-pane
              #projects-favorite.tab-pane
              #projects-complete.tab-pane

        .panel.panel-default
          .panel-heading
            h3 My Ratings & Reviews
            .detail 4.8 from 5 Reviews
          .panel-body
            .ratings.list-group.plain
              .rating.list-group-item
                .list-group-item-heading
                  .detail May 2016
                  span Project Title
                  span.m-l-1= specialist.render_stars
                .list-group-item-text
                  p Dramatically visualize customer directed convergence without revolutionary ROI. Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits.