config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  delete 'subscriptions/:id', to: 'subscriptions#cancel', as: 'cancel_subscription'
  delete 'ported_subscriptions/:id', to: 'subscriptions#specialist_cancel', as: 'specialist_cancel_subscription'
  put 'subscriptions/:id', to: 'subscriptions#update', as: 'update_subscription'

  if Rails.env.production? || Rails.env.staging?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username == ENV.fetch('SIDEKIQ_USERNAME') && password == ENV.fetch('SIDEKIQ_PASSWORD')
    end
  end
  mount Sidekiq::Web => '/sidekiq'

  devise_for :admin_users, ActiveAdmin::Devise.config
  begin
    ActiveAdmin.routes(self)
  rescue ActiveRecord::StatementInvalid, PG::UndefinedTable => e
    Rails.logger.info "ActiveAdmin could not load: #{e.message}"
  end
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  } do
  end

  devise_scope :user do
    get '/squarespace' => 'users/sessions#squarespace'
    get '/squarespace_destroy' => 'users/sessions#squarespace_destroy'
  end

  root to: 'landing_page#show'
  get 'app_config' => 'home#app_config', format: 'js'
  get 'marketplace' => 'home#marketplace'
  get 'r/:token' => 'referrals#show', as: :referrals
  get 'q-and-a-forum' => 'home#q_and_a_forum', as: :q_and_a_forum

  get '/ask-a-specialist/search' => 'forum_questions#search', as: :forum_search
  resources :forum_questions, path: 'ask-a-specialist', param: :url
  resources :forum_answers, only: :create
  get '/ask-a-specialist/upvote/:id' => 'forum_votes#upvote'
  get '/ask-a-specialist/downvote/:id' => 'forum_votes#downvote'
  get '/forum_subscriptions/create' => 'forum_subscriptions#create'
  get '/forum_subscriptions/upgrade' => 'forum_subscriptions#upgrade'
  get '/forum_subscriptions/cancel' => 'forum_subscriptions#cancel'

  get '/notifications_settings' => 'notifications#route'

  get '/exams/:uuid' => 'exams#show'

  resources :turnkey_pages, only: %i[index show create new], path: 'turnkey'
  #  resources :turnkey_solutions # , only: :create
  post '/turnkey/:id' => 'turnkey_pages#create'
  patch '/turnkey/:id' => 'turnkey_pages#update'
  get '/mute_project/:id' => 'project_mutes#toggle'

  resources :feedback_requests, only: %i[create new]
  resources :businesses, only: %i[new create show]
  resource :business, only: %i[edit] do
    patch '/' => 'businesses#update', as: :update
  end
  get '/business' => 'business_dashboard#show', as: :business_dashboard

  concern :favoriteable do
    resources :favorites, only: [] do
      post :toggle, on: :collection
    end
  end
  resources :flags, only: %i[new create]

  namespace :business do
    get '/personalize' => 'personalize#quiz'
    post '/personalize' => 'personalize#quiz'
    get '/personalize_book' => 'personalize#book'
    get '/onboarding' => 'onboarding#index'
    post '/onboarding' => 'onboarding#subscribe'
    get '/upgrade' => 'upgrade#index'
    get '/upgrade/buy' => 'upgrade#buy'
    post '/upgrade/buy' => 'upgrade#subscribe'
    resources :risks, only: %i[index show]
    get '/reports/risks' => 'reports#risks'
    get '/reports/organizations' => 'reports#organizations'
    get '/reports/financials' => 'reports#financials'
    resources :file_folders, only: %i[index show]
    resources :exam_management, only: %i[index show] do
      get :portal, on: :member
    end
    resources :file_docs
    resources :upgrade
    resources :addons, only: %i[index]
    resources :seats, only: %i[index new] do
      delete :unassign
      post :assign
    end
    post '/seats/buy' => 'seats#buy'
    resources :compliance_policies, only: %i[show index] do
      get :entire, on: :collection
    end
    get 'annual_reviews/:id/:revcat', to: 'annual_reviews#revcat'
    resources :annual_reviews, only: %i[new create show destroy index edit update]
    resources :annual_reports, only: %i[new create index update]
    resources :teams, only: %i[new create show edit index update destroy]
    resources :team_members, only: %i[new create edit update destroy]
    resources :tasks, only: %i[new update create destroy show edit index]
    resources :audit_requests, only: %i[index update create new edit show destroy]
    put '/audit_requests' => 'audit_requests#update'
    resource :help, only: :show do
      resource :questions
    end
    resource :projects, only: %i[index]

    get '/projects/new/:local_project_id' => 'projects#new'

    get 'settings' => 'settings#show'
    get 'settings/:id' => 'settings#show'

    get 'profile' => 'profile#show'

    resources :specialists, only: :index
    concerns :favoriteable
    resources :messages
    resources :financials do
      get :invoice, on: :member
    end

    get 'projects/:project_id/interview/:specialist_username' => 'project_dashboard#show', as: :project_dashboard_interview
    get 'projects/:project_id/dashboard' => 'project_dashboard#show', as: :project_dashboard

    scope 'projects/:project_id' do
      resources :project_messages, path: 'messages(/:specialist_username)'
      resources :project_ends, path: 'end'
      resources :project_extensions, path: 'extension'
      resource :project_rating, path: 'rating'
      resource :project_overview, path: 'overview(/:specialist_username)', only: :show
    end

    get 'project_posts/:id' => 'projects#show_post'
    get 'project_posts/:id/edit' => 'projects#update_post'

    resources :projects do
      post :post, on: :member
      get :copy, on: :member

      resources :job_applications, path: 'applications'
      resources :hires
      resources :documents, path: 'documents(/:specialist_username)'
      resources :answers, only: :create
      resources :flags, only: %i[new create]
      resources :timesheets
      resources :project_issues, path: 'issues'
    end

    resources :job_applications do
      post :shortlist
      post :hide
    end
  end

  resources :tos_agreement, only: %i[create]

  resources :employees, path: 'employee', only: %i[new create index]
  # get '/employees/mirror/:business_id', to: 'employees#mirror', as: 'mirror_business'
  # get '/employees/stop-mirror', to: 'employees#stop_mirror', as: 'stop_mirror_business'
  resources :reminders, only: ['index']
  namespace :specialists, path: 'specialist' do
    get '/onboarding' => 'onboarding#index'
    post '/onboarding' => 'onboarding#subscribe'
    get '/' => 'dashboard#show', as: :dashboard
    get '/locked' => 'dashboard#locked'
    resources :tasks, only: %i[new update create destroy edit show index]
    resources :addons, only: %i[index]
    resource :help, only: :show do
      resource :questions
    end
    get 'profile' => 'profile#show'
    get 'settings/:page', to: 'settings#show', page: /general|users|roles|security|subscriptions|billings|notifications/
    resource :settings, only: :show do
      resource :password
      resource :contact_information, only: %i[show update]
      # resource :referrals, only: :show
      resources :subscription_settings, as: :subscriptions, path: 'subscriptions', only: %i[index update]
      resource :delete_account
      resources :delete_managed_accounts, only: :destroy
      resource :payment_settings, as: :payment, path: 'payment' do
        get :new_card
        post :create_card
        post :create_bank
        delete 'delete_card/:id', to: 'payment_settings#delete_card', as: 'delete_card'
        patch 'make_primary/:id', to: 'payment_settings#make_primary', as: 'make_primary'
        patch '/specialist/settings/payment/:id/validate', to: 'payment_settings#validate', as: 'validate'
      end
      resource :team

      resources :bank_accounts do
        patch :make_primary
      end
      resources :notification_settings, as: :notifications, path: 'notifications', only: %i[index update]
    end

    resources :ported_businesses, only: %i[index new create]
    get '/ported_businesses/buy' => 'ported_businesses#buy'
    post '/ported_businesses/buy' => 'ported_businesses#subscribe'
    delete '/ported_businesses/:id', to: 'ported_businesses#delete', as: 'delete_ported_businesses'
    resources :invitations, only: %i[create destroy]
    resources :projects, path: 'my-projects'
    concerns :favoriteable
    resources :messages
    resources :financials do
      get :invoice, on: :member
    end
  end

  get '/specialistmarketplace' => 'specialists#index'
  resources :specialists, only: %i[index new create show]
  get '/profile/:id', to: 'specialists#edit', as: 'employee_profile'
  resource :specialist, only: %i[edit] do
    patch '/' => 'specialists#update', as: :update
  end

  resources :project_invites, path: 'invite'

  resources :projects, only: %i[index show] do
    scope module: 'projects' do
      resources :job_applications, path: 'applications'
      resource :dashboard, only: :show
      resources :messages
      resources :documents
      resources :questions, only: :create
      resources :flags, only: %i[new create]
      resources :timesheets
      resources :issues
      resources :shares
      resource :project_end, path: 'end', as: :end
      resource :project_extension, path: 'extension', as: :extension
      resource :rating
      resource :overview, only: :show
    end
  end

  resources :notifications
  resources :email_threads, path: 'email', only: :create

  namespace :stripe do
    resources :webhooks, only: :create
  end

  namespace :api do
    get 'static_collection' => 'static_collection#index'
    post 'exams/:uuid' => 'exams#email'
    patch 'exams/:uuid' => 'exams#show'

    resources :skills, only: :index
    resources :users, only: [] do
      collection do
        post :sign_in, to: 'authentication#create'
        delete :sign_out, to: 'authentication#destroy'
        post :password, to: 'passwords#create'
        put :password, to: 'passwords#update'
      end

app/views/turnkeys/index.html.slim
.page-parallax.parallax-window data-image-src=asset_url("turnkey/index-header.jpg") data-parallax="scroll"
.container.p-b-3
  .row
    .col-md-6.left-story.text-center
      p.text-center
        | START TAKING CONTROL OF YOUR
        br
        | COMPLIANCE PROGRAM
      .arrow-down
        #comp-jgg2183osvg.style-isy6271e1_comp-jgg2183o.style-isy6271e1_non-scaling-stroke.style-isy6271e1svg style="fill-opacity: 1; stroke-width: 0; stroke: rgb(237, 21, 102); stroke-opacity: 1; fill: rgb(0, 0, 0);" 
          svg preserveaspectratio=("xMidYMid meet") role="img" style=("stroke-width: 0px;") viewbox=("4.360000133514404 20.79199981689453 191.8350830078125 43.78700256347656") xmlns="http://www.w3.org/2000/svg" 
            g
              path d=("M192.05 39H42V24.161c0-2.073-2.057-3.369-3.853-2.333L6.156 40.353c-1.796 1.037-1.749 3.628.047 4.665l31.922 18.524C39.919 64.579 42 63.283 42 61.21V46h150.05a3.501 3.501 0 1 0 0-7z") 

      = link_to "Get started", new_user_registration_path, "data-dismiss" => "modal", "data-remote" => true, class: "btn btn-primary p-h-3 m-t-1"
    .col-md-6.right-story
      h1.text-center.brand-color.p-b-1 IT'S GOOD TO HAVE OPTIONS
      = image_tag "turnkey/document.png"
      h3 ONE OFF PROJECTS
      ul
        li Onsite CCO support
        li Form ADV, 13F, 13H filings, etc.
        li Compliance manual updates
        li Email reviews
        li Look back/internal reviews
        li Secondments
      = image_tag "turnkey/key.png"
      h3 TURN KEY SOLUTIONS
      ul
        li FINRA, SEC, NFA registrations
        li New compliance manuals
        li Mock SEC exams
        li Annual RIA compliance retainer packages
        li Outsourced compliance officers
      = image_tag "turnkey/network.png"
      h3 ENTERPRISE SOLUTIONS
      ul
        li 
          | Fully customized scope of work for when you need an entire team of specialists:
          ul
            li e.g. AML special project teams (KYC, SARS, EDD, red flag alerts, etc.)
.row.black_thing.m-t-3
.container.turnkey-index.m-t-3
  .row
    h1.brand-color Turnkey Solutions
    - for category in @categories do
      .col-md-4.col-sm-6 ontouchstart="this.classList.toggle('hover');"
        .turnkey-index-entity
          .turnkey-index-entity-front
            .turnkey-index-entity-front-bg
            .text-center
              .cost = category.cost
              = link_to category.title, "/turnkey/#{category.url}"
          .turnkey-index-entity-back onclick="window.open('/turnkey/#{category.url}')"
            .text-center.p-l-2.p-r-2 = category.description
.row.enterprise-solutions
  .container
    .row
      h1.brand-color.text-center. Enterprise Solutions
      = simple_form_for FeedbackRequest.new do |f|
        .col-md-4.col-md-push-2
          = f.input :name, placeholder: "Name *"
          = f.input :email, placeholder: "Email *"
          = f.input :phone, placeholder: "Phone number *"
          = f.input :specialists, placeholder: "No. specialists needed"
          = f.input :budget, placeholder: "Budget (USD)"
        .col-md-4.col-md-push-2
          = f.input :description, placeholder: "Project description *"
        .col-md-8.col-md-push-2.p-b-1 = f.submit "Submit", class: "btn btn-primary btn-xs pull-right m-t-1 m-b-3"
.row.black-line
.container.p-b-2
  .row.p-b-3
    .col-md-10.col-md-push-1.find-out-more.p-b-3.m-b-3.p-t-3
      h1.text-center.m-t-0.m-b-2 Ready to find out more?
      .col-md-4.text-center
        .line.m-t-2.m-b-3
        = link_to "FREE EVALUATION", new_feedback_request_path, "data-dismiss" => "modal", "data-remote" => true, class: "btn btn-primary p-h-3 m-t-1"
      .col-md-8.p-t-1
        | Whether you are a seasoned compliance professional or just setting up shop and learning the ropes, we are here as that unbiased third party to help you navigate comptalk you through your needs. You can reach us by email or phone to request your free evaluation and assistance to scope out the best project fit for your circumstances. Just drop us a line!