config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  delete 'subscriptions/:id', to: 'subscriptions#cancel', as: 'cancel_subscription'
  delete 'ported_subscriptions/:id', to: 'subscriptions#specialist_cancel', as: 'specialist_cancel_subscription'
  put 'subscriptions/:id', to: 'subscriptions#update', as: 'update_subscription'

  if Rails.env.production? || Rails.env.staging?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username == ENV.fetch('SIDEKIQ_USERNAME') && password == ENV.fetch('SIDEKIQ_PASSWORD')
    end
  end
  mount Sidekiq::Web => '/sidekiq'

  devise_for :admin_users, ActiveAdmin::Devise.config
  begin
    ActiveAdmin.routes(self)
  rescue ActiveRecord::StatementInvalid, PG::UndefinedTable => e
    Rails.logger.info "ActiveAdmin could not load: #{e.message}"
  end
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  } do
  end

  devise_scope :user do
    get '/squarespace' => 'users/sessions#squarespace'
    get '/squarespace_destroy' => 'users/sessions#squarespace_destroy'
  end

  root to: 'landing_page#show'
  get 'app_config' => 'home#app_config', format: 'js'
  get 'marketplace' => 'home#marketplace'
  get 'r/:token' => 'referrals#show', as: :referrals
  get 'q-and-a-forum' => 'home#q_and_a_forum', as: :q_and_a_forum

  get '/ask-a-specialist/search' => 'forum_questions#search', as: :forum_search
  resources :forum_questions, path: 'ask-a-specialist', param: :url
  resources :forum_answers, only: :create
  get '/ask-a-specialist/upvote/:id' => 'forum_votes#upvote'
  get '/ask-a-specialist/downvote/:id' => 'forum_votes#downvote'
  get '/forum_subscriptions/create' => 'forum_subscriptions#create'
  get '/forum_subscriptions/upgrade' => 'forum_subscriptions#upgrade'
  get '/forum_subscriptions/cancel' => 'forum_subscriptions#cancel'

  get '/notifications_settings' => 'notifications#route'

  get '/exams/:uuid' => 'exams#show'

  resources :turnkey_pages, only: %i[index show create new], path: 'turnkey'
  #  resources :turnkey_solutions # , only: :create
  post '/turnkey/:id' => 'turnkey_pages#create'
  patch '/turnkey/:id' => 'turnkey_pages#update'
  get '/mute_project/:id' => 'project_mutes#toggle'

  resources :feedback_requests, only: %i[create new]
  resources :businesses, only: %i[new create show]
  resource :business, only: %i[edit] do
    patch '/' => 'businesses#update', as: :update
  end
  get '/business' => 'business_dashboard#show', as: :business_dashboard

  concern :favoriteable do
    resources :favorites, only: [] do
      post :toggle, on: :collection
    end
  end
  resources :flags, only: %i[new create]

  namespace :business do
    get '/personalize' => 'personalize#quiz'
    post '/personalize' => 'personalize#quiz'
    get '/personalize_book' => 'personalize#book'
    get '/onboarding' => 'onboarding#index'
    post '/onboarding' => 'onboarding#subscribe'
    get '/upgrade' => 'upgrade#index'
    get '/upgrade/buy' => 'upgrade#buy'
    post '/upgrade/buy' => 'upgrade#subscribe'
    resources :risks, only: %i[index show]
    get '/reports/risks' => 'reports#risks'
    get '/reports/organizations' => 'reports#organizations'
    get '/reports/financials' => 'reports#financials'
    resources :file_folders, only: %i[index show]
    resources :exam_management, only: %i[index show] do
      get :portal, on: :member
    end
    resources :file_docs
    resources :upgrade
    resources :addons, only: %i[index]
    resources :seats, only: %i[index new] do
      delete :unassign
      post :assign
    end
    post '/seats/buy' => 'seats#buy'
    resources :compliance_policies, only: %i[show index] do
      get :entire, on: :collection
    end
    get 'annual_reviews/:id/:revcat', to: 'annual_reviews#revcat'
    resources :annual_reviews, only: %i[new create show destroy index edit update]
    resources :annual_reports, only: %i[new create index update]
    resources :teams, only: %i[new create show edit index update destroy]
    resources :team_members, only: %i[new create edit update destroy]
    resources :tasks, only: %i[new update create destroy show edit index]
    resources :audit_requests, only: %i[index update create new edit show destroy]
    put '/audit_requests' => 'audit_requests#update'
    resource :help, only: :show do
      resource :questions
    end
    resource :projects, only: %i[index]

    get '/projects/new/:local_project_id' => 'projects#new'

    get 'settings' => 'settings#show'
    get 'settings/:id' => 'settings#show'

    get 'profile' => 'profile#show'

    resources :specialists, only: :index
    concerns :favoriteable
    resources :messages
    resources :financials do
      get :invoice, on: :member
    end

    get 'projects/:project_id/interview/:specialist_username' => 'project_dashboard#show', as: :project_dashboard_interview
    get 'projects/:project_id/dashboard' => 'project_dashboard#show', as: :project_dashboard

    scope 'projects/:project_id' do
      resources :project_messages, path: 'messages(/:specialist_username)'
      resources :project_ends, path: 'end'
      resources :project_extensions, path: 'extension'
      resource :project_rating, path: 'rating'
      resource :project_overview, path: 'overview(/:specialist_username)', only: :show
    end

    get 'project_posts/:id' => 'projects#show_post'
    get 'project_posts/:id/edit' => 'projects#update_post'

    resources :projects do
      post :post, on: :member
      get :copy, on: :member

      resources :job_applications, path: 'applications'
      resources :hires
      resources :documents, path: 'documents(/:specialist_username)'
      resources :answers, only: :create
      resources :flags, only: %i[new create]
      resources :timesheets
      resources :project_issues, path: 'issues'
    end

    resources :job_applications do
      post :shortlist
      post :hide
    end
  end

  resources :tos_agreement, only: %i[create]

  resources :employees, path: 'employee', only: %i[new create index]
  # get '/employees/mirror/:business_id', to: 'employees#mirror', as: 'mirror_business'
  # get '/employees/stop-mirror', to: 'employees#stop_mirror', as: 'stop_mirror_business'
  resources :reminders, only: ['index']
  namespace :specialists, path: 'specialist' do
    get '/onboarding' => 'onboarding#index'
    post '/onboarding' => 'onboarding#subscribe'
    get '/' => 'dashboard#show', as: :dashboard
    get '/locked' => 'dashboard#locked'
    resources :tasks, only: %i[new update create destroy edit show index]
    resources :addons, only: %i[index]
    resource :help, only: :show do
      resource :questions
    end
    get 'profile' => 'profile#show'
    get 'settings/:page', to: 'settings#show', page: /general|users|roles|security|subscriptions|billings|notifications/
    resource :settings, only: :show do
      resource :password
      resource :contact_information, only: %i[show update]
      # resource :referrals, only: :show
      resources :subscription_settings, as: :subscriptions, path: 'subscriptions', only: %i[index update]
      resource :delete_account
      resources :delete_managed_accounts, only: :destroy
      resource :payment_settings, as: :payment, path: 'payment' do
        get :new_card
        post :create_card
        post :create_bank
        delete 'delete_card/:id', to: 'payment_settings#delete_card', as: 'delete_card'
        patch 'make_primary/:id', to: 'payment_settings#make_primary', as: 'make_primary'
        patch '/specialist/settings/payment/:id/validate', to: 'payment_settings#validate', as: 'validate'
      end
      resource :team

      resources :bank_accounts do
        patch :make_primary
      end
      resources :notification_settings, as: :notifications, path: 'notifications', only: %i[index update]
    end

    resources :ported_businesses, only: %i[index new create]
    get '/ported_businesses/buy' => 'ported_businesses#buy'
    post '/ported_businesses/buy' => 'ported_businesses#subscribe'
    delete '/ported_businesses/:id', to: 'ported_businesses#delete', as: 'delete_ported_businesses'
    resources :invitations, only: %i[create destroy]
    resources :projects, path: 'my-projects'
    concerns :favoriteable
    resources :messages
    resources :financials do
      get :invoice, on: :member
    end
  end

  get '/specialistmarketplace' => 'specialists#index'
  resources :specialists, only: %i[index new create show]
  get '/profile/:id', to: 'specialists#edit', as: 'employee_profile'
  resource :specialist, only: %i[edit] do
    patch '/' => 'specialists#update', as: :update
  end

  resources :project_invites, path: 'invite'

  resources :projects, only: %i[index show] do
    scope module: 'projects' do
      resources :job_applications, path: 'applications'
      resource :dashboard, only: :show
      resources :messages
      resources :documents
      resources :questions, only: :create
      resources :flags, only: %i[new create]
      resources :timesheets
      resources :issues
      resources :shares
      resource :project_end, path: 'end', as: :end
      resource :project_extension, path: 'extension', as: :extension
      resource :rating
      resource :overview, only: :show
    end
  end

  resources :notifications
  resources :email_threads, path: 'email', only: :create

  namespace :stripe do
    resources :webhooks, only: :create
  end

  namespace :api do
    get 'static_collection' => 'static_collection#index'
    post 'exams/:uuid' => 'exams#email'
    patch 'exams/:uuid' => 'exams#show'

    resources :skills, only: :index
    resources :users, only: [] do
      collection do
        post :sign_in, to: 'authentication#create'
        delete :sign_out, to: 'authentication#destroy'
        post :password, to: 'passwords#create'
        put :password, to: 'passwords#update'
      end

app/models/project/ending.rb
# frozen_string_literal: true

class Project::Ending < Project
  def self.process!(project)
    project.complete!
    project.timesheets.pending.destroy_all
    PaymentCycle.for(project).create_charges_and_reschedule!
    Notification::Deliver.project_ended!(project)
  end

  def self.ends_in_24!(project)
    return if project.ends_in_24
    project.update(ends_in_24: true)
    Notification::Deliver.ends_in_24!(project)
  end
end

app/controllers/api/business/projects_controller.rb
# frozen_string_literal: true

class Api::Business::ProjectsController < ApiController
  before_action :require_business!
  before_action :build_project, only: %i[create]
  before_action :find_project, only: %i[show update destroy]

  skip_before_action :verify_authenticity_token # TODO: proper authentication

  def create
    if project_params[:status] == 'draft'
      @project.save(validate: false)
      @project = build_local_project(@project) unless @project.local_project_id
      respond_with @project, serializer: ProjectSerializer
    elsif policy(@project).post? && @project.validate
      @project.post!
      @project.new_project_notification
      @project = build_local_project(@project) unless @project.local_project_id
      respond_with @project, serializer: ProjectSerializer
    else
      render json: @project.errors, status: :unprocessable_entity
    end
  end

  def update
    @project = Project::Form.find(@project.id)
    src_status = @project.status
    if project_params[:status] == 'draft'
      @project.assign_attributes project_params
      @project.save(validate: false)
    elsif @project.update(project_params)
      @project.post! if project_params[:status] != 'draft' || src_status == 'published'
      respond_with @project, serializer: ProjectSerializer
    else
      render json: @project.errors, status: :unprocessable_entity
    end
  end

  def destroy
    if @project.specialist_id.nil? && @project.destroy
      respond_with @project, serializer: ProjectSerializer
    else
      render json: (@project.errors.keys.count.positive? ? @project.errors : { error: I18n.t('api.business.projects.project_has_specialist') }.to_json),
             status: :unprocessable_entity
    end
  end

  def show
    respond_with @project, serializer: ProjectSerializer
  end

  private

  def build_local_project(project)
    local_project_params = project.attributes.slice('business_id', 'title', 'description', 'starts_on', 'ends_on')
    local_project = LocalProject.create(local_project_params)
    project.update_attribute('local_project_id', local_project.id)
    project
  end

  def build_project
    @project = Project::Form.new(business: current_user.business).tap do |project|
      project.assign_attributes project_params
    end
  end

  def project_params
    params.permit(
      :local_project_id,
      :title,
      :type,
      :location_type,
      :location,
      :lat,
      :lng,
      :description,
      :key_deliverables,
      :role_details,
      :duration_type,
      :estimated_days,
      :starts_on,
      :full_time_starts_on,
      :ends_on,
      :applicant_selection,
      :pricing_type,
      :hourly_payment_schedule,
      :fixed_payment_schedule,
      :hourly_rate,
      :upper_hourly_rate,
      :fixed_budget,
      :estimated_hours,
      :minimum_experience,
      :only_regulators,
      :annual_salary,
      :fee_type,
      :invite_id,
      :est_budget,
      :status,
      :color,
      :specialist_id,
      jurisdiction_ids: [],
      industry_ids: [],
      skill_names: []
    )
  end

  def find_project
    @project = current_business.projects.find(params[:id])
  end
end

app/controllers/api/specialist/projects_controller.rb
# frozen_string_literal: true

class Api::Specialist::ProjectsController < ApiController
  before_action :require_specialist!
  before_action :retrieve_project, only: %i[local calendar_show calendar_hide]
  skip_before_action :verify_authenticity_token # TODO: proper authentication

  def index
    results = Project::Search.new(search_params).results
    respond_with paginate results, each_serializer: ProjectSerializer
  end

  def show
    project = policy_scope(Project).find(params[:id])
    respond_with project, serializer: ProjectSerializer
  end

  def my
    respond_with paginate current_specialist.projects.active +
                          current_specialist.applied_projects.visible, each_serializer: ProjectSerializer
  end

  def local
    respond_with @project.local_project, serializer: LocalProjectSerializer
  end

  def calendar_hide
    lproject = @project.local_project
    current_user.hide_local_project(lproject.id)
    respond_with lproject, serializer: LocalProjectSerializer
  end

  def calendar_show
    lproject = @project.local_project
    current_user.show_local_project(lproject.id)
    respond_with lproject, serializer: LocalProjectSerializer
  end

  private

  def retrieve_project
    @project = policy_scope(Project).find(params[:project_id])
  end

  def search_params
    params.permit(
      :project_type, :sort_by, :keyword, :regulator, :location_type, :location, :location_range,
      :lat, :lng, :page, :pricing_type,
      industry_ids: [], jurisdiction_ids: [], skill_names: [], experience: [], budget: [], duration: []
    )
  end
end

app/controllers/projects/dashboards_controller.rb
# frozen_string_literal: true

class Projects::DashboardsController < ApplicationController
  prepend_before_action :find_project, only: :show
  prepend_before_action :require_specialist!
  before_action :redirect_if_full_time
  # skip_before_action :check_unrated_project, if: -> { action_name == 'show' && @project&.requires_specialist_rating? }

  def show
    if @project.rfp?
      applications = @project.job_applications.where(specialist_id: current_specialist.id)
      @project.populate_rfp(applications[0]) if applications.count.positive?
    end
  end

  private

  def redirect_if_full_time
    redirect_to specialists_dashboard_path if @project&.full_time?
  end

  def find_project
    projects = current_specialist.projects.where(id: params[:project_id])
    projects = current_specialist.applied_projects.where(id: params[:project_id]) if projects.blank?
    @project = projects.first
  end
end

app/controllers/projects/documents_controller.rb
# frozen_string_literal: true

class Projects::DocumentsController < DocumentsController
end

app/controllers/projects/flags_controller.rb
# frozen_string_literal: true

class Projects::FlagsController < ApplicationController
  before_action :find_project

  def new; end

  def create
    @flag = Flag::Create.call(current_specialist, find_flagged_content, reason: flag_params[:reason].values.join(', '))
    redirect_to project_path(@project)
  end

  private

  def find_project
    @project = Project.find(params[:project_id])
  end

  def flag_params
    params.require(:flag).permit(:answer_id, :question_id, reason: %i[i h s])
  end

  def find_flagged_content
    if flag_params[:question_id].present?
      Question.find(flag_params[:question_id])
    elsif flag_params[:answer_id].present?
      Answer.find(flag_params[:answer_id])
    end
  end
end

app/controllers/projects/issues_controller.rb
# frozen_string_literal: true

class Projects::IssuesController < ApplicationController
  before_action :require_specialist!
  before_action :find_project

  def new
    respond_to do |format|
      format.js
    end
  end

  def create
    @issue = ProjectIssue::Create.call(@project, issue_params)
    respond_to do |format|
      format.js do
        render :new unless @issue.persisted?
      end
    end
  end

  private

  def issue_params
    params.require(:project_issue).permit(:issue, :desired_resolution).merge(user_id: current_user.id)
  end

  def find_project
    @project = current_specialist.projects.find(params[:project_id])
  end
end

app/views/projects/_cards.html.slim
- if @projects.empty?
  h2.text-center.m-b-2 No projects yet

.row
  - @projects.map(&method(:decorate)).each do |project|
    .card-container.col-xs-12.col-md-6.col-lg-4 data-project-id=project.id
      .project.card.panel.panel-default class="#{project.type}-project"
        a.panel-heading href=project_path(project)
          - if project.applicants_count > 0
            .label.label-danger
              i.icon.maxicons1-peoples
              span= project.applicants_count
          h4= project.title

        a.panel-body href=project_path(project)
          .icon-list
            .item
              i.icon.maxicons2-navigation
              span= project.location_details
            .item
              i.icon.maxicons1-building
              span= project.industries.map(&:name).to_sentence
            .item
              i.icon.maxicons1-earth
              span= project.jurisdictions.map(&:name).to_sentence
            .item
              i.icon.maxicons2-clock
              span= project.start_and_duration
            .item
              i.icon.maxicons1-dollar
              span= project.dollars
            .item
              - if project.one_off?
                i.icon.maxicons1-wallet
                span= project.payment_schedule_humanized
              - else
                span &nbsp;

        .panel-footer
          .btn-group
            - if project.draft_or_review?
              a.btn.btn-md.btn-primary href=edit_project_path(project)
                i.icon.maxicons2-editor
                span Edit
              = link_to project_path(project), class: 'btn btn-md btn-primary'
                i.icon.maxicons2-fix.flip-x
                span Post
            - elsif project.pending?
              a.btn.btn-md.btn-primary.btn-single href="#"
                i.icon.maxicons1-peoples
                span Applicants
            - elsif project.active?
              a.btn.btn-md.btn-primary.btn-single href=project_path(project)
                i.icon.maxicons2-view
                span View
            - else # project.complete?
              a.btn.btn-md.btn-primary href=copy_project_path(project.id)
                i.icon.maxicons1-copy
                span Copy
              a.btn.btn-md.btn-primary href=project_path(project)
                i.icon.maxicons2-view
                span View

- if @projects.total_pages > 1
  .dot-pagination.m-b-1
    - @projects.total_pages.times do |n|
      = link_to ''.html_safe, current_uri(page: n + 1), remote: true, class: "page #{"current" if n + 1 == @projects.current_page}"

app/views/projects/_form.html.slim
= simple_form_for project, remote: true, authenticity_token: true, wrapper: :inline_form, html: { class: "project_form", data: { "project-type" => project.type } } do |f|
  .text-center
    h1.m-t-0.m-b-3 Is this a one-off project or a full-time role?

    = f.input :type, as: :radio_pills, collection: [['Project', Project.types[:one_off]], ['Full Time', Project.types[:full_time]]], btn_class: 'btn-lg btn-default p-x-3', wrapper_html: { class: 'm-b-0' }

  .well.well-lg.m-t-3.project-details data-location-type=project.location_type
    h2.text-center.m-b-2.full-time Job Details
    h2.text-center.m-b-2.one-off Project Details
    .row.row-compact
      .col-xs-12.col-sm-4
        = f.input :title, input_html: { class: 'input-lg' }
        = f.input :location_type, collection: Project::LOCATIONS, include_blank: I18n.t('simple_form.placeholders.project.location_type'), input_html: { class: 'input-lg js-select' }
        = f.input :location, input_html: { class: "input-lg" }
        = project.industries_input(f)
      .col-xs-12.col-sm-8
        = f.input :description, as: :text, input_html: { class: 'input-lg tt-n', maxlength: 750 }
    .row.row-compact
      .col-xs-12.col-sm-4
        = project.jurisdictions_input(f)
      .col-xs-12.col-sm-8
        = f.input :key_deliverables, input_html: { class: 'input-lg tt-n' }
        = f.input :full_time_starts_on, input_html: { class: 'input-lg js-datepicker', "data-value" => (l(f.object.full_time_starts_on, format: :pickadate) if f.object.full_time_starts_on.present?) }

  .well.well-lg.m-t-3.project-duration
    h2.text-center.m-b-2 Project Duration
    .row.row-compact.js-date-range
      .col-xs-12.col-sm-6
        = f.input :starts_on, required: true, as: :string, input_html: { class: 'input-lg js-datepicker', data: { 'date-from' => true, value: (l(f.object.starts_on, format: :pickadate) if f.object.starts_on) } }
      .col-xs-12.col-sm-6
        = f.input :ends_on, required: true, as: :string, input_html: { class: 'input-lg js-datepicker', data: { 'date-to' => true, value: (l(f.object.ends_on, format: :pickadate) if f.object.ends_on) } }
    .row.row-compact.p-b-1
      .col-xs-12
        .small.text-muted Please estimate if necessary to allow our specialists to determine their availability. You will be able to extend the deadline later.

  .well.well-lg.m-t-3.project-salary
    h2.text-center.m-b-2 Salary
    .row.row-compact
      .col-xs-12.col-sm-6
        = f.input :annual_salary, as: :string, required: true, input_html: { class: 'input-lg', data: { masked: '0#' } }
      .col-xs-12.col-sm-6
        = f.input :fee_type, as: :radio_pills, collection: [%w(Upfront upfront), %w(Monthly monthly)], btn_class: 'btn-lg tt-u btn-default p-x-3'
        button.info-tooltip type="button" data-toggle="tooltip" title="Select how you'd like to pay Complect's fees" i
    .row.row-compact.text-muted.small.p-b-1
      .col-xs-12
        'Note: Complect offers two payment options for the full-time hiring fee:
        br
        '(1) 15% of first year salary payable on the new employee's start date, refundable if employee leaves within 90 days.
        br
        '(2) 3% of first year salary payable monthly for 6 months beginning on the new employee's start date. If employee  leaves within 6 months, monthly payments are no longer due after termination date.

  .well.well-lg.m-t-3.project-pricing data-pricing-type=project.pricing_type
    h2.text-center.m-b-2 Project Pricing
    .row.row-compact.m-y-1
      .col-xs-12.text-center
        = f.input :pricing_type, as: :radio_pills, collection: [%w(Hourly hourly), %w(Fixed fixed)], btn_class: 'btn-default p-x-3 tt-u'
    .row.row-compact
      .col-xs-12.col-sm-4
        = project.hourly_payment_schedule_input(f)
        = project.fixed_payment_schedule_input(f)
      .col-xs-12.col-sm-4
        = project.hourly_rate_input(f)
        = project.fixed_budget_input(f)
      .col-xs-12.col-sm-4
        = f.input :estimated_hours, as: :string, require: true, input_html: { class: 'input-lg', data: { masked: '0#' } }
    .row.row-compact.p-b-1
      .col-xs-12
        .small.text-muted Note: Complect adds a 10% fee on top of your project value. You can read more about our Payment Terms <a class="text-muted" href="#">here</a>.

  .well.well-lg.m-t-3
    h2.text-center.m-b-2 Applicant Prerequisites
    .row.row-compact.m-y-1
      .col-xs-12.col-sm-6
        = f.input :minimum_experience, include_blank: t('simple_form.placeholders.project.minimum_experience'), collection: Project::MINIMUM_EXPERIENCE, input_html: { class: 'input-lg js-select' }
        .form-group.project_only_regulators
          span.checkbox
            = f.check_box :only_regulators
            = f.label :only_regulators
      .col-xs-12.col-sm-6
        = project.skills_input(f)
        button.info-tooltip type="button" data-toggle="tooltip" title="Only hashtag up to ten skills your desired specialist MUST possess. Desired skills can also be referenced in the project description." i
        .form-group.m-t-1.m-b-0
          ul.skills-required
            - project.skill_names.each do |skill|
              li
                input type='hidden' name='project[skill_names][]' value=skill
                span= skill
                span.remove data-skill=skill x

  - if f.object.errors.any?
    .clearfix.m-y-3
      .alert.alert-danger.text-center.col-xs-12.col-sm-8.col-sm-push-2.m-b-0
        - if f.object.errors[:base].any?
          = f.object.errors[:base].join(' ')
        - else
          'Oops! You are missing important information, please add it before proceeding.

  .m-t-3.actions
    - if project.persisted?
      = link_to project, method: :delete, data: { confirm: project.confirm_delete, 'confirm-label' => 'Delete' }, class: 'btn btn-muted btn-lg m-r-1' do
        .fa.fa-trash-o
        span Delete
    - else
      = link_to_back default: business_dashboard_path, data: { method: 'get', confirm: project.confirm_delete, 'confirm-label' => 'Delete' }, class: 'btn btn-muted btn-md m-r-1' do
        .fa.fa-trash-o
        span Delete
    button.btn.btn-primary.btn-lg.m-r-1 type="submit" name="project[status]" value=Project.statuses[:draft]
      i.icon.maxicons2-editor
      span Save as Draft
    button.btn.btn-primary.btn-lg type="submit" name="project[status]" value=Project.statuses[:review]
      i.icon.maxicons2-fix.flip-x
      span Review & Post

  .row.m-t-2.text-center
    .col-xs-12.col-sm-8.col-sm-push-2.small.text-muted
      p You will be able to make changes to this information until you receive your first application.
        If you need to make changes after that, contact us at <a class="text-muted" href="mailto:help@complect.co">help@complect.co</a> or on [phone number].